pub mod account;
pub mod account_reject_reason;
pub mod account_update;
pub mod address;
pub mod api_list;
pub mod balance;
pub mod balance_transaction;
pub mod bitcoin_receiver;
pub mod card;
pub mod charge;
pub mod coupon;
pub mod create_charge;
pub mod customer;
pub mod date_of_birth;
pub mod delete;
pub mod discount;
pub mod dispute;
pub mod event;
pub mod interval;
pub mod legal_entity;
pub mod money;
pub mod owner;
pub mod refund;
pub mod shipping;
pub mod source;
pub mod source_type;
pub mod subscription;
pub mod transfer;
pub mod update_charge;
pub mod verification;

pub use account::*;
pub use account_reject_reason::*;
pub use account_update::*;
pub use address::*;
pub use api_list::*;
pub use balance::*;
pub use balance_transaction::*;
pub use bitcoin_receiver::*;
pub use card::*;
pub use charge::*;
pub use coupon::*;
pub use create_charge::*;
pub use customer::*;
pub use date_of_birth::*;
pub use delete::*;
pub use discount::*;
pub use dispute::*;
pub use event::*;
pub use interval::*;
pub use legal_entity::*;
pub use money::*;
pub use owner::*;
pub use refund::*;
pub use shipping::*;
pub use source::*;
pub use source_type::*;
pub use subscription::*;
pub use transfer::*;
pub use update_charge::*;
pub use verification::*;

use serde::de::Deserialize;
use std::fmt::Debug;

pub trait StripeObject : Clone + Debug + Deserialize {
    fn id(&self) -> &str;
}
